### ISSUE TITLE
Velodyne and A*

### ISSUE THREAD

**Issue by va9abund** [karlkurzer/path_planner#12]
Dear Karl,
I've been trying to reach the state you've shown at video "Path Planning with a Hybrid A* Algorithm and Sensor Fusion", but haven't succeed.

At the begging I thought it would be enough to launch velodyne_arlanda.launch, then I tried to dig deeper and found out that in this package there ain't any subscriber to PointCloud or LaserScan. Could you provide names of missing nodes/packages?

**Comment by karlkurzer** [comment]
Hey Aleksander,

well the launch file was for another rosbag and node, which I haven't commited. Since the planner works on a occupancy grid any way to serve such a grid to the planner will suffice for it to generate a plan.

I hope that helps.
