### ISSUE TITLE
planner does not take obstacles into account as soon as cellsize or resolution (in .yaml file describing the map) is not equal to 1

### ISSUE THREAD

**Issue by Yvonnn** [karlkurzer/path_planner#15]
Everything is in the title

**Comment by karlkurzer** [comment]
hey, did you ajust the length of the motion primitives for the new cell size?

https://github.com/karlkurzer/path_planner/blob/b102a3252e0c949d7106bd85d6a0dda3b130b7ef/src/node3d.cpp#L14)

...
