### ISSUE TITLE
I changed a map file,and it doesn't work

### ISSUE THREAD

**Issue by yuhuabing** [karlkurzer/path_planner#16]
Hi karl:
I changed a map, but the program has no output path points.
This is my modified yaml file：
    image: willo.pgm
    resolution: 0.05
    origin: [-26.600000, -28.200000, 0.000000]
    negate: 0
    occupied_thresh: 0.65
    free_thresh: 0.196
Can you tell me how to modify the program?Thank you！

**Comment by karlkurzer** [comment]
tbh. I never used it with grids smaller grid cells smaller than 0.5m. However, it should be possible, some adjustments need to be made to the motion primitives as they should be at least: <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\small&space;\sqrt(2a^2)" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\inline&space;\small&space;\sqrt(2a^2)" title="\small \sqrt(2a^2)" /></a> with a being the side length of a cell: https://github.com/karlkurzer/path_planner/blob/39705972c28008cc8f2dcf77b4af106d187667a5/src/node3d.cpp#L14

**Comment by yuhuabing** [comment]
What does “a” mean? For my 0.05 resolution, how should dy and dx and dt be modified, because I don't understand the algorithm, so I don't know how to modify it.
Thank you！
