### ISSUE TITLE
How to set the start position and goal position manually? And how to use a dynamical map? Is there a demo for dynamical map?

### ISSUE THREAD

**Issue by abc283646346** [karlkurzer/path_planner#18]
Thank you for your code! It's very nice, and I'm interested in it.
But I have meet two problems.
One is How to set the start position and goal position manually? I used the "rostopic pub -1 ..." to publish the two topics. But after running one command, the command will latch for 3 seconds, then  another command can be allowed to run. Is there a demo for setting the the start position and goal position manually?
The other problem is how  to use a dynamical map? And is there a dynamical map demo for us to use? I want to simulate a  scenario like a real car travelling. Is it suitable for this code to do the simulation?
Thank you for your guidance!

**Comment by karlkurzer** [comment]
Hey,

thanks:

- Click 2D Pose Estimate to set a start point on the map (`p`)
- Click 2D Nav Goal to set a goal point on the map (`g`)

As for the dynamic planning, yes it is possible, see the video below.

https://www.youtube.com/watch?v=GwIU00jukO4

You just have to start the planner for each update of the map.

**Comment by abc283646346** [comment]
Thank you for your guiding! 
And is  your update map coming from the sensors of the car?
If I want a simulation demo of update map, I maybe have to draw it by myself. Is that right?
I'm sorry to borrow you again!

**Comment by PigletPh** [comment]
> Hey,
> 
> thanks:
> 
> * Click 2D Pose Estimate to set a start point on the map (`p`)
> * Click 2D Nav Goal to set a goal point on the map (`g`)
> 
> As for the dynamic planning, yes it is possible, see the video below.
> 
> https://www.youtube.com/watch?v=GwIU00jukO4
> 
> You just have to start the planner for each update of the map.

How to achieve effects in video

**Comment by PigletPh** [comment]
> Hey,
> 
> thanks:
> 
> * Click 2D Pose Estimate to set a start point on the map (`p`)
> * Click 2D Nav Goal to set a goal point on the map (`g`)
> 
> As for the dynamic planning, yes it is possible, see the video below.
> 
> https://www.youtube.com/watch?v=GwIU00jukO4
> 
> You just have to start the planner for each update of the map.

Thanks for your excellent work to share. How to achieve the effect in the video？
Is there any codes to study?Thanks!

**Comment by karlkurzer** [comment]
The video is from the planner running in an open-loop fashion based on a recorded trajectory and Lidar point cloud information. Have a look at https://github.com/karlkurzer/path_planner/blob/5f3166e04fc295619d84a4a80b9497aef3cbea24/include/constants.h#LL35-L35C33 and https://github.com/karlkurzer/path_planner/blob/master/launch/velodyne_arlanda.launch.
