### ISSUE TITLE
I tried to implement your Hybrid A* on a custom map, but after generating the path the node crashes.

### ISSUE THREAD

**Issue by jonnyrules96** [karlkurzer/path_planner#19]
I am trying to implement your hybrid A* on a map that is of size 1100 x 423, and for some reason, the search crashes after correctly finding the path to the end goal. Is there a work around in the code for this? Or is there a line that we need to account for?

**Comment by karlkurzer** [comment]
That's a very specific questions, I am not sure. I would suggest that you should look into `gdb` and generate a back trace for that error. The code is obviously experimental and was written at a time where I wasn't very proficient in C++.

**Comment by ShenoyVaradaraya** [comment]
if you increase the number of the iterations in the `constants.h` file.. you can give consecutive start and goals.
