### ISSUE TITLE
As a plugin in the move_base package

### ISSUE THREAD

**Issue by TBJ1027** [karlkurzer/path_planner#28]
Hey, I want to replace the global_planner in move_base package with this algorithm. Have u done this before? Could u please give me some suggestions? Thanks a lot!

**Comment by karlkurzer** [comment]
Hey, actually I haven't done this, but I am sure it shouldn't be that hard. Good Luck!

**Comment by TBJ1027** [comment]
Thanx again for responding! I will try it!

**Comment by vinnnyr** [comment]
@TBJ1027 I am currently attempting to make this work with move base flex. Will try to update here if successful.

**Comment by badaolaziang** [comment]
> @TBJ1027 I am currently attempting to make this work with move base flex. Will try to update here if successful.

have you succeed yet?

**Comment by badaolaziang** [comment]
@vinnnyr have you succeed adding it as a plugin?

**Comment by vinnnyr** [comment]
I have not, unfortunately I got distracted away from this work
