### ISSUE TITLE
The problems of choose of dx dy dt.

### ISSUE THREAD

**Issue by zhangxingyu1206** [karlkurzer/path_planner#29]
hi, @karlkurzer 
Many thanks for the nice code of your contribution. 
The step parameters:
// R = 6, 6.75 DEG
const float Node3D::dy[] = { 0,        -0.0415893,  0.0415893};
const float Node3D::dx[] = { 0.7068582,   0.705224,   0.705224};
const float Node3D::dt[] = { 0,         0.1178097,   -0.1178097};
when the vehicle driving forward and turn left,  dx ,dy and dt  should be positive.But,in the situation i=1, the step parameters dy is negative. Can you provide some reasons of doing so?Thank you very much.

**Comment by karlkurzer** [comment]
>  when the vehicle driving forward and turn left, dx ,dy and dt should be positive.But,in the situation i=1, the step parameters dy is negative. Can you provide some reasons of doing so?Thank you very much.

I am not sure why you think that this needs to be the case. It depends on the orientation of your coordinate system. In this case the coordinate system is defined, in this case the axis are flipped.

**Comment by zhangxingyu1206** [comment]
![](https://raw.githubusercontent.com/zgh551/FigureBed/master/img/20200115100321.png)
Acoording to your defination of [dx dy dt], I plot the figure. No mater what kind of coordinate system, when the dx is positive and dy is nagative, the dt should be negative. But, in the figure, dt is positive,the  the position for a driving car is not possible.
In my opinion, the [dx dy dt] is shown below.
![](https://raw.githubusercontent.com/zgh551/FigureBed/master/img/20200115100316.png)

**Comment by karlkurzer** [comment]
I see - without looking into the code I'd assume, that the heading is also flipped (clockwise). That would be the only option, right?

**Comment by zhangxingyu1206** [comment]
In your coordinate system,the heading theta increment is positive when the rotation direction is clockwise?

**Comment by karlkurzer** [comment]
That's a guess - it's been four years - so I am not entirely sure in what way I defined the coordinate system and the positive direction of rotation. Sorry for the inconclusive answer.

**Comment by EthanCodesss** [comment]
> In your coordinate system,the heading theta increment is positive when the rotation direction is clockwise?

Hello! How to compute the value of dx, dy, dt? I don't understand why [0.705224, 0.0415893, 0.1178097]. 
Thanks for help!
