### ISSUE TITLE
Why the angle is 6.75°？

### ISSUE THREAD

**Issue by yu2014ol** [karlkurzer/path_planner#36]
According to the description in the paper, shouldn't it be 5°?
```C++
// R = 6, 6.75 DEG
const float Node3D::dy[] = { 0,        -0.0415893,  0.0415893};
const float Node3D::dx[] = { 0.7068582,   0.705224,   0.705224};
const float Node3D::dt[] = { 0,         0.1178097,   -0.1178097};
```

**Comment by karlkurzer** [comment]
I don't recall the exact values, but if the code says that the turning radius is 6m and the resulting change in heading 6.75 deg, then it's likely correct. You might as well do the math and see, if the values work out.
