### ISSUE TITLE
question regard to tiebreaker

### ISSUE THREAD

**Issue by JialiangHan** [karlkurzer/path_planner#38]
Hi, Karl,

thank you for your great work and sharing the code, i have read your paper and have some questions regard to how to choose this tiebreaker.
tiebreaker here is to break the admissible of heuristic function, you choose 0.01, but when i have a different turning radius, this value should also be changed? should this value be a function of turning radius or something else?

thank you.
Jialiang Han

**Comment by karlkurzer** [comment]
Hey @JialiangHan a tie braker is only used to make the successor more attractive then the predecessor. Depending on your cost structure you have to choose it. The turning radius has no direct influence IMHO. So you could debug the cost for same cell explansions and see how much the predecessor vs the successor in the same cell is and adjust your value accordingly.
