### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by garychian** [karlkurzer/path_planner#39]
Sorry, this is my first time to implement code in ROS.  The catkin_ws/src floder was been created and the code was clone into src. But when I try to catkin_make in the root folder, it gives me errors say cannot find package.xml. So I copied package.xml to root floder(under src), but when I catkin_make it again. 
I get below error:

CMake Error at CMakeLists.txt:76 (add_executable):
  Cannot find source file:

    src/main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:57 (add_library):
  Cannot find source file:

    /home/garychian/catkin_ws_path_planner/src/src/algorithm.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:73 (add_executable):
  Cannot find source file:

    src/tf_broadcaster.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

I am so confused right now, the CMakeLists.txt was auto generated by ROS(I think), so what about the CMakeLists.txt under path_planner floder?

anyone can give me some suggestions? Thanks in advantage!

**Comment by karlkurzer** [comment]
@garychian please look at some tutorials (e.g. http://wiki.ros.org/ROS/Tutorials). There should not be any issues with the code, since the CI pipeline runs fine.

**Comment by garychian** [comment]
> @garychian please look at some tutorials (e.g. http://wiki.ros.org/ROS/Tutorials). There should not be any issues with the code, since the CI pipeline runs fine.

OK, thanks. Do we need more dependencies to run catkin_make?
