### ISSUE TITLE
Problems with map resolution

### ISSUE THREAD

**Issue by HongboZhang95713** [karlkurzer/path_planner#40]
Hi Karl, thx for sharing your codes, they help me a lot!

I got some problems by using maps with resolution of 0.05. I've seen this problem in many other issues, so I changed dy[] dx[] in class node2D and class node3D, I just multiply them by 20 and I also changed Constants::cellSize to 0.05, still it doesn't work! The results are wired, besides it took very long time. Do you have some ideas where I can fix it?  

![prob3](https://user-images.githubusercontent.com/73024824/101884195-45caf800-3bd3-11eb-9558-8a04371fc6e6.png)
![prob2](https://user-images.githubusercontent.com/73024824/101884199-46fc2500-3bd3-11eb-84e5-0bb90fd3255d.png)
![prob1](https://user-images.githubusercontent.com/73024824/101884202-4794bb80-3bd3-11eb-96ae-c2e75482d85d.png)

**Comment by karlkurzer** [comment]
I think this has to do with some hard coded values, the code is not very adaptive, meaning a change in cell size probably requires different motion primitives, checking of the collision checker etc. The reason why it takes longer is that a higher resolution increases the number of cells dramatically, so if you go to a cell size of 1/10 it means 100 times more cells, meaning much more to compute. I hope this helps even though if it is not the answer you have hoped for :-)

**Comment by WeiJunREN** [comment]
> Hi Karl, thx for sharing your codes, they help me a lot!
> 
> I got some problems by using maps with resolution of 0.05. I've seen this problem in many other issues, so I changed dy[] dx[] in class node2D and class node3D, I just multiply them by 20 and I also changed Constants::cellSize to 0.05, still it doesn't work! The results are wired, besides it took very long time. Do you have some ideas where I can fix it?
> 
> ![prob3](https://user-images.githubusercontent.com/73024824/101884195-45caf800-3bd3-11eb-9558-8a04371fc6e6.png) ![prob2](https://user-images.githubusercontent.com/73024824/101884199-46fc2500-3bd3-11eb-84e5-0bb90fd3255d.png) ![prob1](https://user-images.githubusercontent.com/73024824/101884202-4794bb80-3bd3-11eb-96ae-c2e75482d85d.png)

Hey, does this problem resolved finally?

**Comment by karlkurzer** [comment]
No, this repository is not actively being maintained.
