### ISSUE TITLE
Dynamic Planner Empty Path

### ISSUE THREAD

**Issue by bektaskemal** [karlkurzer/path_planner#42]
I would like to do dynamic planning which uses online generated map. I am generating map using gmapping and set manual false. But I get empty path as result. Any idea on what is wrong?
Could you please an example(launch file etc.) for dynamic case?

Edit: I made it work. But it doesn't work when map origin is not (0,0).

**Comment by ixtiyoruz** [comment]
> I would like to do dynamic planning which uses online generated map. I am generating map using gmapping and set manual false. But I get empty path as result. Any idea on what is wrong?
> Could you please an example(launch file etc.) for dynamic case?
> 
> Edit: I made it work. But it doesn't work when map origin is not (0,0).

Hi can you please elaborate the steps you did ?  How did you move the map origin to (0,0) ?

**Comment by moritzkuhl** [comment]
How did you get your dynamic occupancy grid map to have the location (0,0)? currently the position of my dynamic occupancy grid map seems to be -2.5, -1,0. 

What i have done so far to make this algorithm work for dynamic occupancy grid maps:

- put the manual bool to false /// A flag for the mode (true = manual; false = dynamic). Manual for static map or dynamic for dynamic map.
- changed the subsribed topic in planner to the topic where my occupancy grid map gets published

The node seems to crash after the roslaunch. 

Any tips???
