### ISSUE TITLE
How to navigate a real robot with occupancy map provided by other packages?

### ISSUE THREAD

**Issue by yunxdai** [karlkurzer/path_planner#45]
Thanks a lot for this fantastic work! Currently I'm working on integrating this package on my own robot platform. Since you mentioned this package was tested on your own vehicle, could you please give some suggestions on how this package receives occupancy map which is updated online by other perception packages, and how to interact with the ROS navigation stack for navigation? It would be better if you can provide detailed instructions!

**Comment by jtoobias** [comment]
Did you happen to figure out the way to integrate this with the navigation stack for move base? I'm currently looking at changing the code so it can work with move base (nav_core::BaseGlobalPlanner) as a plugin but was hoping that there is an already defined way or an easy method that I am overlooking.

**Comment by yunxdai** [comment]
> Did you happen to figure out the way to integrate this with the navigation stack for move base? I'm currently looking at changing the code so it can work with move base (nav_core::BaseGlobalPlanner) as a plugin but was hoping that there is an already defined way or an easy method that I am overlooking.

Sorry, but I didn't find out the way to integrate this repo with move_base. Actually, I set aside this work after this issue, so I didn't investigate deep into this problem. If you manage to do it, could you please share the method?
