### ISSUE TITLE
Port to ROS2

### ISSUE THREAD

**Issue by guilyx** [karlkurzer/path_planner#46]
Hi,

Is there any plan to port the project to ROS2 ?
If not, I might try to sync it with either Foxy, Galactic or Rolling.

Let me know :)

**Comment by karlkurzer** [comment]
Hey,

currently I am too involved with my PhD project, so that I doubt that I would be porting it to ROS2 anytime soon, however it would be great to have at least a ROS2 branch for people that have that requirement.

Personally I would go for Galactic Geochelone :-)

Best
Karl

**Comment by SteveMacenski** [comment]
ROS 2 Navigation (Nav2) already has its own Hybrid-A* planner implementation internally now https://github.com/ros-planning/navigation2/tree/main/nav2_smac_planner. You can find configuration docs here https://navigation.ros.org/configuration/packages/configuring-smac-planner.html

Steve

**Comment by karlkurzer** [comment]
@SteveMacenski true - I've forgotten about that since I am not working on this anymore. I guess for anyone wanting to use ROS2 that stack makes more sense.
