### ISSUE TITLE
Driving direction

### ISSUE THREAD

**Issue by Manu0130** [karlkurzer/path_planner#47]
Hey Karl,

I am relatively new to ROS and have a question regarding output data. I would like to find out the driving direction of the vehicle. In the visualization tool a change of direction is clearly visible, but it is not reflected in the topics (for example in /sPathVehicle). Is there a possibility that I am overlooking?

As I understand the code a direction change is taken into account in the path selection, however the selected direction is then not published.

Thanks a lot for your help.

With kind regards

**Comment by karlkurzer** [comment]
That's a good question :-) I took a quick look, but I suppose that I just don't publish that information. How is the change in direction reflected in rviz? That could be an indication where to look for that information in the code.

Best
Karl

**Comment by Manu0130** [comment]
Thanks a lot for the really quick reply.

With the reference to the visualization I only meant that a change of direction is visually recognizable when looking at the path.

Also in the visualization tool rviz I think the information is not directly available.

At which point in the code is the final information about the direction of travel available? Unfortunately, this is not directly recognizable to me. I would really appreciate it if you could help me out here.

With kind regards

**Comment by karlkurzer** [comment]
Hey, the direction is being determined here (and following), but I don't think it's annotated anywhere: https://github.com/karlkurzer/path_planner/blob/1441cdfd988b237703ff888247c4a63c5630bc30/src/node3d.cpp#L75
