### ISSUE TITLE
car center node is within the map while the car area is out of map

### ISSUE THREAD

**Issue by yslenjoy** [karlkurzer/path_planner#51]
`isOnGrid` function only performs the car center node check, it doesn't perform any car area check, which may result issue like picture below.

To solve this issue, we can simply do some modifications in collisionDetection.cpp for `CollisionDetection::configurationTest` function:
 -- letting the collision check **return false** if any car area is out of the map
```
if (cX >= 0 && (unsigned int)cX < grid->info.width && cY >= 0 && (unsigned int)cY < grid->info.height) {
      if (grid->data[cY * grid->info.width + cX]) {
        return false;
      }
    }
   // modification below:
    else{
      return false;
    }
```

![0601 - notOnGrid](https://user-images.githubusercontent.com/30484964/171371076-5908fbce-684b-4d4a-8f62-75e8e7071752.png)

**Comment by karlkurzer** [comment]
That's a valid point, I only considered planning for areas with occupancy information :-)
