### ISSUE TITLE
Weights of Voronoi and Curvature terms are 0

### ISSUE THREAD

**Issue by anmoliiitd823** [karlkurzer/path_planner#6]
Hey, 
Most probably this was intentional but I just wanted to know the reason for keeping these weights 0(in file smoother.h) and what all impacts will it have on changing them.
If we are setting the weights to zero then it means that these terms won't have any effect in the final P then why are we consuming time in calculating the other terms as we know that Pvor and Pcur will turn out to be zero due to their weight being 0.
If I change the value of these weights will it have any effect on the computation time of the algorithm?
Can someone kindly brief on the results for the different value of these weights?

Thank You

**Comment by toby4548** [comment]
According to Kurzer, "Voronoi weight, influences the impact on the path". You can find this part in Ch. 6.3.4 of his thesis [here](http://kth.diva-portal.org/smash/record.jsf?pid=diva2%3A1057261&dswid=6398).

**Comment by anmoliiitd823** [comment]
I have read the thesis and it's really well written but in the code, the weights of these terms are set to zero.
Yes but a zero weight means that it won't have any impact on the path , so if that's the case then why are we even computing it.
So I am assuming that these weights are independent of the environment and the car so what would be the best way to find the most suited weights in terms of accuracy.
Also, I am curious to know that whether the change in weights has an effect on computation time of the algorithm?

**Comment by toby4548** [comment]
I think that he just offers the flexibility if you want to use it.

**Comment by karlkurzer** [comment]
yes, exactly feel free to use them :-). Basically the Voronoi part is making sure that the distance kept to obstacles is similar for the right and left side, ensuring that a tightening is passed in the middle. The curvature term should smooth the path, however this part is not entirely stable, thus it might result in unexpected solutions, hence it is set to 0. If you want to save some time computing these values just exclude them, however I don't believe it will speed up the process much, as it is just the post processing.

I hope that helps.

**Comment by anmoliiitd823** [comment]
@karlkurzer Thanks a lot.

**Comment by santhosh46** [comment]
Hi, can someone clarify about the "dvor" (notation according to KarlKurzer report in 6.3.4 section) or "dv" (according to the "Practical Search Techniques in Path Planning for Autonomous Driving" paper by Thrun Et al., in Path-Cost Function Using the Voronoi Field section) term in the Voronoi Field equation ? It was mentioned as the edge of Generalized Voronoi Diagram but was not described clearly. If anyone has knowledge about it, please comment.
Thanks in advance :)

**Comment by chen0510566** [comment]
actually, there is two bugs in the smoothing algorithm. 
the formula in the paper is wrong!

**Comment by LawranceXcl** [comment]
> actually, there is two bugs in the smoothing algorithm.
> the formula in the paper is wrong!

@chen0510566 where are the bugs ?Thks.

**Comment by SteveMacenski** [comment]
@chen0510566 any update / comments you can provide?

**Comment by chen0510566** [comment]
> > actually, there is two bugs in the smoothing algorithm.
> > the formula in the paper is wrong!
> 
> @chen0510566 where are the bugs ?Thks.

i can't remeber exactly.
i guess the formula in the paper Practical Search Techniques in Path Planning for Autonomous Driving, the partial deriative of curvature on x is wrong.
