### ISSUE TITLE
confusing resolution

### ISSUE THREAD

**Issue by zhthree3** [karlkurzer/path_planner#63]
only both map_resolution and Constants::cellSize are equal to 1, it will run normally.

**Comment by zhthree3** [comment]
Can you tell me if the unit of the [input path point coordinates] for smooth function is [pixel], [grid], or [m]？

**Comment by karlkurzer** [comment]
@zhthree3 I usually use SI units, hence it ought to be m, I hope that helps 🙂!

**Comment by zhthree3** [comment]
I don't think the unit is [m], because the input of the DynamicVoronoi is pixels, you directly input the path points into the DynamicVoronoi in Smooth function, such as the following code in Smoother::voronoiTerm(Vector2D xi):
`float obsDst = voronoi.getDistance(xi.getX(), xi.getY());`
