### ISSUE TITLE
Code not working for 500x500 image/matrix

### ISSUE THREAD

**Issue by anmoliiitd823** [karlkurzer/path_planner#7]
Whenever I try for a 500x500 image/matrix the hybrid_a_star crashes within a few seconds but it works for 450x450 , I am not able to find the problem due to which this is occurring. What should I do to make it work for the a 500x500 grid .

**Steps to reproduce the error**
1) Take a 500x500 image and put it in the maps folder 
2) Put the name of the image in maps.yaml
3) roslaunch as given in readme
4) Set the markers ... after 2-3 markers set the hybrid_a_star node should crash

Thank You

**Comment by karlkurzer** [comment]
Have you figured it out yet, I have been very busy lately and have only little time now and then to answer some questions.
