### ISSUE TITLE
Potential errors in smoother.cpp

### ISSUE THREAD

**Issue by facontidavide** [karlkurzer/path_planner#9]
Hi,

There are some pretty nasty warning in __smoother.cpp__.
Smoother::voronoiTerm() seems to be broken (unused variables and no return).

Davide

**Comment by karlkurzer** [comment]
Hey, could you a bit more precise about what is not working :-)? Thanks

**Comment by facontidavide** [comment]
Look at the method. You do not return anything

**Comment by facontidavide** [comment]
Additionally, you are using not initialized variables

**Comment by facontidavide** [comment]
https://github.com/karlkurzer/path_planner/blob/master/src/smoother.cpp#L121-L155

You don't initialize any variable and you don't return gradient. Is that specific enough ;)

**Comment by karlkurzer** [comment]
Hey Davide,

thanks for the hints, the code is fairly old by now and apparently I was missing a Voronoi implementation that allowed me to get the edge distance, hence I know commented the code removing the warnings 453864b55202283019380a941be50daacb4a06a0.

Thanks again :-)
